# Generated by Django 2.2.5 on 2019-09-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domains',
            name='authority',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='domains',
            name='publisher',
            field=models.IntegerField(),
        ),
    ]
