# Generated by Django 2.2.5 on 2019-09-04 14:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190902_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='domains',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 4, 14, 59, 41, 139267)),
        ),
        migrations.CreateModel(
            name='DomainsDeleted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=30000)),
                ('publisher', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=30)),
                ('authority', models.CharField(blank=True, max_length=100)),
                ('deleted_at', models.DateTimeField(default=datetime.datetime(2019, 9, 4, 14, 59, 41, 139725))),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Source')),
            ],
        ),
    ]
