# Generated by Django 2.2.5 on 2019-09-04 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20190904_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domains',
            name='added_at',
        ),
        migrations.RemoveField(
            model_name='domainsdeleted',
            name='deleted_at',
        ),
    ]
