# Generated by Django 2.2.5 on 2019-09-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20190904_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainsdeleted',
            name='source',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
