# Generated by Django 3.1.7 on 2021-08-18 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_remove_ftp_credential_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftp_credential',
            name='project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.project'),
        ),
    ]
