# Generated by Django 3.1.7 on 2021-08-18 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20210818_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domains',
            name='user_rec',
        ),
    ]
