# Generated by Django 3.1.7 on 2021-08-24 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_domains_user_rec'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DomainsDeleted',
        ),
    ]
